development:
  adapter: async

# Warning: The Async adapter cannot be used in production
# Requires Redis >= 4.0.0
production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: licence_management_system_production

test:
  adapter: test
